### ISSUE TITLE
alex 3.2.7 fails to parse definitions which can pass alex 3.2.6

### ISSUE THREAD

**Issue by Commelina** [simonmar/alex#197] opened 2022-01-21 06:18 UTC
I tried the latest alex 3.2.7 on a common-used library [`language-c`-0.9.0.1](https://hackage.haskell.org/package/language-c). However, it failed to parse [`Lex.x`](https://github.com/visq/language-c/blob/master/src/Language/C/Parser/Lexer.x):
```
src/Language/C/Parser/Lexer.x:123:22: parse error
```
It seems that the problem happened [here](https://github.com/visq/language-c/blob/c67759c5e74ae616ba04f4ff292ad5fd47ad5a43/src/Language/C/Parser/Lexer.x#L123):
```
@iec60559suffix = (32|64|128)[x]?
```

Then I rolled my alex back to version 3.2.6 then everything worked. I am not sure if it is a bug.

**Comment by hasufell** [comment] 2022-01-21 16:22
Same here: https://github.com/haskell/ghcup-metadata/runs/4898784174?check_suite_focus=true#step:8:35

**Comment by Ericson2314** [comment] 2022-01-21 18:45
OK I deprecated 3.2.7 and made it unbuildable. We'll need some new test cases for this.

**Comment by Ericson2314** [comment] 2022-01-21 19:31
@andreasabel Assuming this isn't a crazy bootstrapping issue, it looks like you made all the parser changes between 3.2.6 and 3.2.7. Would have any time to help debug this?

**Comment by andreasabel** [comment] 2022-01-22 08:35
@Ericson2314 : I started to have a look.  Then I hit #195.

**Comment by Ericson2314** [comment] 2022-01-23 07:10
Running info on the happy grammar,
```
...
  58     rep -> '{' CHAR '}'                                (49)
  59     rep -> '{' CHAR ',' '}'                            (50)
  60     rep -> '{' CHAR ',' CHAR '}'                       (51)
  61     rep -> '{' NUM '}'                                 (52)
  62     rep -> '{' NUM ',' '}'                             (53)
  63     rep -> '{' NUM ',' NUM '}'                         (54)
...
  71     set0 -> CHAR                                       (62)
  72     set0 -> CHAR '-' CHAR                              (63)
...
```
The problem is these lower rules don't have `NUM` equivalents.

I think remembering to double up NUM and CHAR is hard, and all the more so when this case we would need to "unparse" the number, yet also preserve things like `001` vs `1`.

This makes makes we think we should not have a `NumT`, and instead just have a number nonterminal, parsed from char terminals. Does that sound good?

**Comment by andreasabel** [comment] 2022-01-23 08:31
Er, @Ericson2314, I am already working on this.  I just lack the repo rights to assign this to me so that you would know about it.

**Comment by andreasabel** [comment] 2022-01-23 17:45
> This makes makes we think we should not have a `NumT`, and instead just have a number nonterminal, parsed from char terminals. Does that sound good?

Yes this sounds good.
I just wish you would not ask me to help and then race for a fix.  Wasted my time, I could have looked into something else.

**Comment by Ericson2314** [comment] 2022-01-23 18:27
> Er, @Ericson2314, I am already working on this. I just lack the repo rights to assign this to me so that you would know about it.

Oh sorry! That's awkward. I should have watched the time zones more carefully, I just assumed you stopped at the bisect.

Yes, let's get you those perms.

**Comment by andreasabel** [comment] 2022-01-23 20:24
I should have stated in text that I am looking into a fix...

PR #202 seems to solve the problem in a satisfactory way, by restricting the parsing of numerals to inside multiplicity expressions `{`_n_,_m_`}`.

**Comment by Ericson2314** [comment] 2022-01-23 20:50
@andreasabel BTW I earlier sent you an email taking the git email address. Is that a fine email address? I want to reach out to @simonmar more directly to get to permissions.

**Comment by andreasabel** [comment] 2022-01-23 21:13
> @andreasabel BTW I earlier sent you an email taking the git email address. Is that a fine email address? I want to reach out to @simonmar more directly to get to permissions.

I found the message.  I am often slow with email, looking into my github notifications more often than my email.

Thanks for your efforts!

**Closed** 2022-01-23 22:55 UTC

**Comment by Ericson2314** [comment] 2022-01-23 23:21
@Commelina and others, please try https://hackage.haskell.org/package/alex-3.2.7.1
